### PR TITLE
Single http calls + add example + poetry 1.2.0

### PR DESCRIPTION
**Pull request by tcompa**
1. Use click context to have a single http call in the client.
2. Add a client/server example.
3. Use poetry 1.2.0 for CI

### CODE REVIEW

**Review by jacopo-exact — CHANGES_REQUESTED** [review]
why is `fractal_server.db` committed? was this really intended?
I would rather commit a script that creates and initialises it as needed.

**Comment by tcompa** [comment]
> why is `fractal_server.db` committed? was this really intended?
> I would rather commit a script that creates and initialises it as needed.

This is because we have the examples in the `fractal` (i.e. client) repo, where we don't have access to what is needed to generate the db (at least the `alembic.ini` file). Then I generated an empty db from within the server repo, and copied it here to be used in the examples.

**Comment by jacopo-exact** [comment]
> > why is `fractal_server.db` committed? was this really intended?
> > I would rather commit a script that creates and initialises it as needed.
> 
> This is because we have the examples in the `fractal` (i.e. client) repo, where we don't have access to what is needed to generate the db (at least the `alembic.ini` file). Then I generated an empty db from within the server repo, and copied it here to be used in the examples.

For how things are set up, `pip install fractal-server` will also install alembic. Furthermore, `fractal-server` is a dev dependency of fractal-client.

I still think we should avoid committing binaries unless we can't do otherwise.

**Comment by tcompa** [comment]
> I still think we should avoid committing binaries unless we can't do otherwise.

Agreed. This was clearly a workaround.

> For how things are set up, `pip install fractal-server` will also install alembic. Furthermore, `fractal-server` is a dev dependency of fractal-client.

At the moment I failed to reproduce the db from an arbitrary path (i.e. without having to `cd` into `fractal-server` folder). I did the following:
1. I copied `fractal-server`'s `alembic.ini` to my current folder (`fractal/examples/.../server`).
2. I created `fractal_server/migrations/versions`, to match the expected folders.
3. I copied `fractal_server/migrations/env.py` to the same relative path within the current folder.

Then I run
```
alembic revision --autogenerate -m "new revision"
```
and I get
```
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
2022-09-08 13:19:51,735 INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO  [sqlalchemy.engine.Engine] BEGIN (implicit)
2022-09-08 13:19:51,735 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("alembic_version")
INFO  [sqlalchemy.engine.Engine] PRAGMA main.table_info("alembic_version")
2022-09-08 13:19:51,735 INFO sqlalchemy.engine.Engine [raw sql] ()
INFO  [sqlalchemy.engine.Engine] [raw sql] ()
2022-09-08 13:19:51,739 INFO sqlalchemy.engine.Engine SELECT alembic_version.version_num 
FROM alembic_version
INFO  [sqlalchemy.engine.Engine] SELECT alembic_version.version_num 
FROM alembic_version
2022-09-08 13:19:51,739 INFO sqlalchemy.engine.Engine [generated in 0.00011s] ()
INFO  [sqlalchemy.engine.Engine] [generated in 0.00011s] ()
2022-09-08 13:19:51,742 INFO sqlalchemy.engine.Engine ROLLBACK
INFO  [sqlalchemy.engine.Engine] ROLLBACK
ERROR [alembic.util.messaging] Can't locate revision identified by '9a8f60d500df'
  FAILED: Can't locate revision identified by '9a8f60d500df'
```

Is this a trivial error? I cannot really understand where it comes from.

**Comment by tcompa** [comment]
[This answer](https://stackoverflow.com/a/32356600/19085332) (dropping a table from the db) seems to solve the problem, although I don't why I would have to do it (it was not necessary, when running alembic from within the server repo).

**Comment by tcompa** [comment]
I will commit a new version asap, with a script to re-create the db

**Comment by tcompa** [comment]
I removed the committed db, and now re-create it every time we run the example. Everything looks good (AKA the workflow gets submitted, via parsl), both locally and on on pelkmanslab.

FYI, the new `server_config_and_start.sh` looks like this
```bash
#!/bin/bash

# Create an empty db
rm fractal_server/migrations/versions/*.py -v
rm -r data
mkdir data
alembic revision --autogenerate
alembic upgrade head

# Set environment variables
echo -e "DEPLOYMENT_TYPE=testing\nJWT_SECRET_KEY=secret\nDATA_DIR_ROOT=/tmp/\nSQLITE_PATH=./data/fractal_server.db" > .fractal_server.env

# Start the server
fractal-server
```

And the only glitch I encountered is unrelated to this PR (it concerns running two server instances at the same time: https://github.com/fractal-analytics-platform/fractal-server/issues/25).

On my side, this is good to merge.

**Comment by tcompa** [comment]
Note that this PR now also includes some other "harmless" change (updating poetry version to 1.2.0 in the github CI)

**Review by jacopo-exact — APPROVED** [review]

**Pull request merged**
