### PR TITLE
Merge `server-newtasks` into `server`

### PR DESCRIPTION
**Pull request by tcompa**
The goal of this PR is to port all tasks from the legacy architecture (in the [`tasks` branch](https://github.com/fractal-analytics-platform/fractal/tree/tasks)) to the new server/client one. The focus is on a quick porting, with important updates to current tasks that will be treated somewhere else.

Current tasks porting status:
- [x] `create_zarr_structure` and `yokogawa_to_zarr`: already available before this PR;
- [x] `replicate_zarr_structure` and `maximum_intensity_projection`: preliminary version available with this PR.
Issue: #150.
- [x] `image_labeling` and `image_labeling_whole_well`, to do.
Issue: #152.
- [x] `measurement` (via `napari_worfklows`): the task is complete, in the legacy branch, and we should only port it to the new architecture.
Issue: #164 

Issues that are not strictly required, but will be needed soon:
- `illumination_correction`: this is low-priority for this PR (since it is not necessary to get to the final stages of a worfklow), and it could be treated somewhere else.
Issue: #158 .
- Redefine parsl executors, and the way for users to set them.
Issues: #157 and #168

### CODE REVIEW

**Comment by tcompa** [comment]
Quick comment:U
Until we close https://github.com/fractal-analytics-platform/fractal/issues/157 (scheduled for a different milestone), we cannot run labeling on gpu. This should not be a real issue, since labeling tests already work on cpu with no friction.

**Comment by jluethi** [comment]
@tcompa Hmm, let's make sure that #157 becomes a priority after the server merge then. While yes, we can test on the CPU, performance will be way slower, especially on the 3D side.
We can avoid this by testing on small test sets and mostly doing 2D labeling, but 3D labeling should of course also be supported :)

**Comment by tcompa** [comment]
> We can avoid this by testing on small test sets and mostly doing 2D labeling, but 3D labeling should of course also be supported :)

I'm using a 3D stack of images, for testing, and run times seem under control (I cannot really say now, because of other bugs that prevent me from running it at the moment). The "trick" is always to label the image at a lower resolution, for testing.

**Comment by tcompa** [comment]
I stand corrected, 3D run times are actually a bit longer than I thought.
Still, we can have at least one example running (see https://github.com/fractal-analytics-platform/fractal/issues/152#issuecomment-1232909404), so that the merge can go on without #157.

**Comment by tcompa** [comment]
This is almost ready.
What we'd like to include:
* A quick review by me and @jacopo-exact of how I/O works within the MIP task.
* If we manage, also #157 (in a preliminary version) and #168.

**Comment by tcompa** [comment]
> What we'd like to include:
> 
>     * A quick review by me and @jacopo-exact of how I/O works within the MIP task.

We agreed that the current version is OK, and deferred future work to #139

> * If we manage, also https://github.com/fractal-analytics-platform/fractal/issues/157 (in a preliminary version) and https://github.com/fractal-analytics-platform/fractal/issues/168.

This work started in https://github.com/fractal-analytics-platform/fractal/pull/171 and will continue in a different PR (to be prepared right after this one), still part of https://github.com/fractal-analytics-platform/fractal/milestone/7.

Therefore this PR is ready.

**Pull request merged**
